graph TD

    code --> data
    code --> scripts
    code --> extensions
    code --> docs

    data --> scripts
    data --> tests

    docker --> infra
    docker --> tests

    infra --> tests

    scripts --> tests

    Python --> tests
    TypeScript --> tests
    Bicep --> tests